### ISSUE TITLE
Can't navigate to root directory in windows

### ISSUE THREAD

**Issue by rafaelcastrocouto** [krasimir/yez#9]
In a Yez terminal I can't go to the root directory. 
None of the following works:

      cd /      cd //
      cd \      cd \\
      cd c:/    cd c:\

I can only do it with `cd ..`
A little help please!

**Comment by krasimir** [comment]
There is a new `0.1.10` version released. Open `chrome://extensions` and click on `Update extensions` button so you get the latest one. Then open (reopen if it is opened now) Yez tab and you'll be able to type `cd /`. The issue was that Yez was forming the path using the current working directory. Now if the directory starts with `/` it does not following this approach. Let me know if it works under Windows.

**Comment by rafaelcastrocouto** [comment]
Working 100%. :+1: 
Thx

**Comment by krasimir** [comment]
You are welcome.
